---
title: "Project 4"
author: "Projects R Us (Group 9)"
date: "2022-09-30"
output: pdf_document
---
```{r, include=FALSE}
library(tidyverse) #always
library(ape) #for evo analysis
library(nlme) #ditto
library(MuMIn) #for AIC
library(geiger) #for eco analysis
library(knitr) #for knitting options
```
# Introduction
The *Anolis* are extremely diverse genus that contains over 400 iguanian reptiles. The anoles can be categorized based on their similiar behavior and ecological niche within a group called ecomorphs. This study aimed to research whether the perch height and diameter influences the hind leg and snout-vent length (SVL) relationship across the ecomorphs, taking their phylogeny into account.

# Methods
The morphological and ecological data used for this was derived from the ecomophology study done by Hagey et al.The two data sets were combined into a single log transformed data to be used for analysis. Two simple linear models were constructed for preliminary analysis. The first linear model contained hind limb total(Htotal) predicted by SVL in referenced to the perch height data. The second linear model contained Htotal predicted by SVL in referenced to the perch diameter data. The residual of the two linear models were grouped by their ecomorphs and graphed into two separate boxplot to explore how ecomophormophology could have played a role in the Htotal~SVL relationship in respect to perch height/diameter.

To account for the effect that phylogeny has on the relationship, three phylgenetic least squares (PGLS) models were made under the Brownian model. The phylogeny information was derived from the phylogenetic relatinship study by Poe et al. Two PGLS model was constructed with correlation to perch height and perch diameter respectively. The last PGLS model was constructed with correlation to both perch height and perch diameter. The three models ran through Akaike information criterion (AIC) to determine which model had the best fit. The best fitting model was further analyzed using ANOVA to identify which variable had most effect on the HTotal~SVL relationship. Finally all three PGLS model was graphed using a boxplot graph to observe the difference in residual across the ecomorphs under the three different models.
# Results
# Discussion
# Author Contribution